// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var pointer_sig = "<<pointer>>";

var inline_origin_sig = "<<inline>>";

exports.pointer_sig = pointer_sig;
exports.inline_origin_sig = inline_origin_sig;
/* No side effect */
