// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ExternalJs = require("./external.js");

function fetch_api(prim) {
  return ExternalJs.f(prim);
}

function fetch_id(prim) {
  return ExternalJs.fetch_id(prim);
}

exports.fetch_api = fetch_api;
exports.fetch_id = fetch_id;
/* ./external.js Not a pure module */
